# Generated by Django 3.2 on 2022-08-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesdisplay',
            name='mode',
            field=models.CharField(choices=[('lines', 'Lines')], default='lines', max_length=16),
        ),
    ]
