# Generated by Django 3.2 on 2022-08-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_seriesdisplay_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriesdisplay',
            name='mode',
            field=models.CharField(choices=[('lines', 'Lines'), ('markers', 'Markers'), ('lines+markers', 'Linesmarkers')], default='lines', max_length=16),
        ),
    ]
