# Generated by Django 3.2 on 2022-08-23 07:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_seriesdisplay_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesdisplay',
            name='chart_type',
            field=models.CharField(choices=[('scatter', 'Scatter')], default='scatter', max_length=16),
        ),
        migrations.AddField(
            model_name='seriesdisplay',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
