# Generated by Django 3.2 on 2022-08-23 10:01

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_auto_20220823_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoraMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=20)),
                ('measurement', models.CharField(max_length=50)),
                ('port', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='seriesdisplay',
            name='color',
            field=colorfield.fields.ColorField(default='#0000FF', image_field=None, max_length=18, samples=None),
        ),
    ]
