# Generated by Django 3.2 on 2022-08-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_alter_lorameasurement_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorameasurement',
            name='device_id',
            field=models.CharField(choices=[('0000000000000001', '0000000000000001'), ('0000000000000002', '0000000000000002'), ('0000000000000003', '0000000000000003'), ('0000000000000004', '0000000000000004'), ('0000000000000005', '0000000000000005'), ('0000000000000006', '0000000000000006'), ('0000000000000007', '0000000000000007'), ('0000000000000008', '0000000000000008')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lorameasurement',
            name='measurement',
            field=models.CharField(choices=[('device_frmpayload_data_battery', 'Battery'), ('device_frmpayload_data_ec', 'Ec'), ('device_frmpayload_data_ec0', 'Ec0'), ('device_frmpayload_data_ec2', 'Ec2'), ('device_frmpayload_data_ec_pore0', 'Ec_pore0'), ('device_frmpayload_data_ec_pore2', 'Ec_pore2'), ('device_frmpayload_data_par', 'Par'), ('device_frmpayload_data_soil_vwc0', 'Soil_vwc0'), ('device_frmpayload_data_soil_vwc2', 'Soil_vwc2'), ('device_frmpayload_data_soiless_vwc0', 'Soiless_vwc0'), ('device_frmpayload_data_soiless_vwc2', 'Soiless_vwc2'), ('device_frmpayload_data_temp', 'Temp'), ('device_frmpayload_data_temp0', 'Temp0'), ('device_frmpayload_data_temp2', 'Temp2'), ('device_frmpayload_data_temp3', 'Temp3'), ('device_frmpayload_data_vwc', 'Vwc'), ('device_frmpayload_data_vwc0', 'Vwc0'), ('device_frmpayload_data_vwc02', 'Vwc02'), ('device_frmpayload_data_vwc2', 'Vwc2'), ('device_frmpayload_data_water_potential', 'Water_potential')], max_length=50),
        ),
    ]
