# Generated by Django 3.2 on 2022-08-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0009_seriesdisplay_yaxis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chart Title', max_length=64)),
            ],
        ),
    ]
