# Generated by Django 3.2 on 2022-08-24 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0011_auto_20220824_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 2, 55, 33, 855310, tzinfo=utc)),
        ),
    ]
