# Generated by Django 3.2 on 2022-08-24 03:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0013_alter_chart_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 3, 4, 18, 76468, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='chart',
            name='display_priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Small value has higher priority'),
        ),
    ]
