# Generated by Django 3.2 on 2022-08-24 04:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0014_auto_20220824_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck to prevent displaying'),
        ),
        migrations.AddField(
            model_name='chart',
            name='series_displays',
            field=models.ManyToManyField(blank=True, related_name='in_charts', to='charts.SeriesDisplay'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 4, 52, 6, 367194, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='chart',
            name='display_priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Smaller value has higher priority to appear'),
        ),
    ]
