# Generated by Django 3.2 on 2022-08-24 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0015_auto_20220824_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 5, 11, 12, 364609, tzinfo=utc), editable=False),
        ),
    ]
