# Generated by Django 3.2 on 2022-08-25 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0018_auto_20220825_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 25, 3, 16, 20, 513482, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='seriesdisplay',
            name='yaxis',
            field=models.CharField(choices=[('y1', 'Yaxisleft'), ('y2', 'Yaxisright')], default='y1', max_length=10),
        ),
    ]
